function y = tp1(x)
%TP1 Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the DSP System Toolbox 8.7.
% Generated on: 30-Apr-2015 17:08:52

%#codegen

% To generate C/C++ code from this function use the codegen command. Type
% 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    % % Equiripple Lowpass filter designed using the FIRPM function.
    %
    % % All frequency values are in Hz.
    % Fs = 5438.596;  % Sampling Frequency
    %
    % Fpass = 1259.649;        % Passband Frequency
    % Fstop = 1459.649;        % Stopband Frequency
    % Dpass = 0.057501127785;  % Passband Ripple
    % Dstop = 0.01;            % Stopband Attenuation
    % dens  = 20;              % Density Factor
    %
    % % Calculate the order from the parameters using FIRPMORD.
    % [N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);
    %
    % % Calculate the coefficients using the FIRPM function.
    % b  = firpm(N, Fo, Ao, W, {dens});
    
    Hd = dsp.FIRFilter( ...
        'Numerator', [-0.00508389133995956 0.0102130983284103 ...
        0.0221889397766385 0.0113501334378108 -0.0107309005662951 ...
        -0.00753160528814858 0.014584980948262 0.0100133374942585 ...
        -0.0182686237337105 -0.0136136119755146 0.0233304140464992 ...
        0.0190805950712066 -0.0306261476431292 -0.0278035412724146 ...
        0.0425333432085219 0.0438979887116766 -0.0668909648081166 ...
        -0.0846933421035485 0.153597910225648 0.445677678976132 ...
        0.445677678976132 0.153597910225648 -0.0846933421035485 ...
        -0.0668909648081166 0.0438979887116766 0.0425333432085219 ...
        -0.0278035412724146 -0.0306261476431292 0.0190805950712066 ...
        0.0233304140464992 -0.0136136119755146 -0.0182686237337105 ...
        0.0100133374942585 0.014584980948262 -0.00753160528814858 ...
        -0.0107309005662951 0.0113501334378108 0.0221889397766385 ...
        0.0102130983284103 -0.00508389133995956]);
end

y = step(Hd,x);


% [EOF]
